const js = require("@eslint/js");
const tseslint = require("typescript-eslint");
const importX = require("eslint-plugin-import-x");

const googleRules = {
  "no-cond-assign": "off",
  "no-irregular-whitespace": "error",
  "no-unexpected-multiline": "error",
  "curly": ["error", "multi-line"],
  "guard-for-in": "error",
  "no-caller": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-invalid-this": "error",
  "no-multi-spaces": "error",
  "no-multi-str": "error",
  "no-new-wrappers": "error",
  "no-throw-literal": "error",
  "no-with": "error",
  "prefer-promise-reject-errors": "error",
  "array-bracket-spacing": ["error", "never"],
  "block-spacing": ["error", "never"],
  "brace-style": "error",
  "camelcase": ["error", { properties: "never" }],
  "comma-dangle": ["error", "always-multiline"],
  "comma-spacing": "error",
  "comma-style": "error",
  "computed-property-spacing": "error",
  "eol-last": "error",
  "func-call-spacing": "error",
  "key-spacing": "error",
  "keyword-spacing": "error",
  "linebreak-style": "error",
  "new-cap": "error",
  "no-array-constructor": "error",
  "no-multiple-empty-lines": ["error", { max: 2 }],
  "no-new-object": "error",
  "no-tabs": "error",
  "no-trailing-spaces": "error",
  "object-curly-spacing": "error",
  "one-var": ["error", { var: "never", let: "never", const: "never" }],
  "operator-linebreak": ["error", "after"],
  "padded-blocks": ["error", "never"],
  "quote-props": ["error", "consistent"],
  "quotes": ["error", "single", { allowTemplateLiterals: true }],
  "semi": "error",
  "semi-spacing": "error",
  "space-before-blocks": "error",
  "space-before-function-paren": ["error", { asyncArrow: "always", anonymous: "never", named: "never" }],
  "spaced-comment": ["error", "always"],
  "switch-colon-spacing": "error",
  "arrow-parens": ["error", "always"],
  "generator-star-spacing": ["error", "after"],
  "no-var": "error",
  "prefer-const": ["error", { destructuring: "all" }],
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "rest-spread-spacing": "error",
  "yield-star-spacing": ["error", "after"],
};

module.exports = tseslint.config(
  { ignores: ["lib/**/*", "generated/**/*"] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  importX.flatConfigs.recommended,
  {
    files: ["eslint.config.js"],
    languageOptions: { sourceType: "commonjs" },
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  {
    languageOptions: {
      parserOptions: { sourceType: "module", project: ["tsconfig.json", "tsconfig.dev.json"] },
    },
    plugins: { "@typescript-eslint": tseslint.plugin },
    rules: {
      ...googleRules,
      // Project overrides.
      "quotes": ["error", "double"],
      "indent": ["error", 2],
      "object-curly-spacing": ["error", "always"],
      "max-len": ["error", { code: 120 }],
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": ["error", { args: "none" }],
      "import-x/no-unresolved": "off",
    },
  },
);
